absl-py==0.12.0
affine==2.3.0
arcgis==1.9.0
argon2-cffi==20.1.0
astropy==4.3.1
astunparse==1.6.3
async-generator==1.10
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
backcall==0.2.0
bleach==3.3.0
bokeh==2.3.2
brotlipy==0.7.0
cachetools==4.2.2
Cartopy @ file:///C:/ci/cartopy_1612289996447/work
certifi==2021.5.30
cffi @ file:///C:/ci/cffi_1625831764494/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.0.1
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==1.6.0
colorama==0.4.4
colorcet==2.0.6
colour==0.1.5
cryptography @ file:///C:/ci/cryptography_1616769432139/work
cycler==0.10.0
Cython==0.29.23
dask==2021.6.0
datashader==0.13.0
datashape==0.5.2
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
defusedxml==0.7.1
distributed==2021.6.0
dtreeviz==1.3
entrypoints==0.3
ephem @ file:///C:/ci/ephem_1623920865493/work
et-xmlfile==1.1.0
Fiona==1.8.13.post1
fsspec==2021.6.0
future==0.18.2
gast==0.3.3
GDAL==3.0.2
geopandas @ file:///tmp/build/80754af9/geopandas_1627401391374/work
google-auth==1.31.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
graphviz==0.16
greenlet @ file:///C:/ci/greenlet_1628888257991/work
grpcio==1.38.0
h5py==2.10.0
HeapDict==1.0.1
idna @ file:///tmp/build/80754af9/idna_1622654382723/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1617877486026/work
iniconfig==1.1.1
ipykernel==5.5.5
ipython==7.24.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
joblib @ file:///tmp/build/80754af9/joblib_1613502643832/work
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
jupyterlab-widgets==1.0.0
Keras-Preprocessing==1.1.2
keyring==23.1.0
kiwisolver @ file:///C:/ci/kiwisolver_1612282618948/work
lasio @ file:///C:/Users/nbutter/Desktop/lasio-0.29-py2.py3-none-any.whl
lerc==0.1.0
llvmlite==0.36.0
locket==0.2.1
lxml @ file:///C:/ci/lxml_1616443391272/work
mapclassify @ file:///tmp/build/80754af9/mapclassify_1627369494639/work
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib @ file:///D:/bld/matplotlib-suite_1604871176074/work
matplotlib-inline==0.1.2
mistune==0.8.4
mkl-service==2.3.0
mpi4py==3.0.3
msgpack==1.0.2
multipledispatch==0.6.0
munch==2.5.0
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
networkx @ file:///tmp/build/80754af9/networkx_1627459939258/work
notebook==6.2.0
ntlm-auth==1.5.0
numba @ file:///C:/ci/numba_1616774290339/work
numpy @ file:///D:/bld/numpy_1591485433275/work
oauthlib==3.1.1
obspy @ file:///D:/bld/obspy_1619796059803/work
olefile==0.46
openpyxl==3.0.7
opt-einsum==3.3.0
packaging==20.9
pandas==1.0.1
pandocfilters==1.4.3
param==1.11.1
parso==0.8.2
partd==1.2.0
patsy==0.5.1
pickleshare==0.7.5
Pillow @ file:///C:/ci/pillow_1625663286921/work
pluggy==0.13.1
prometheus-client==0.11.0
prompt-toolkit==3.0.18
protobuf==3.17.3
psutil==5.8.0
py==1.10.0
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyct==0.4.6
pyerfa==2.0.0
Pygments==2.9.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pypiwin32==223
pyproj @ file:///C:/ci/pyproj_1614278152133/work
pyreadr==0.4.2
pyrsistent==0.17.3
pyshp @ file:///home/conda/feedstock_root/build_artifacts/pyshp_1610646860606/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
pytest==6.2.4
python-certifi-win32==1.6
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-snappy==0.6.0
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
pywin32==301
pywin32-ctypes==0.2.0
pywinpty==1.1.2
PyYAML==5.4.1
pyzmq==22.1.0
rasterio==1.1.0
rasterstats==0.14.0
requests @ file:///tmp/build/80754af9/requests_1629994808627/work
requests-kerberos==0.12.0
requests-negotiate-sspi==0.5.2
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
rsa==4.7.2
Rtree @ file:///C:/ci/rtree_1618421019532/work
scikit-learn==0.24.2
scipy==1.4.1
seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work
Send2Trash==1.5.0
setuptools-scm==6.0.1
Shapely==1.7.1
simplejson @ file:///C:/ci/simplejson_1626446657843/work
six @ file:///tmp/build/80754af9/six_1623709665295/work
snuggs==1.4.7
sortedcontainers==2.4.0
spatialpandas==0.4.3
SQLAlchemy @ file:///C:/ci/sqlalchemy_1626948528806/work
statsmodels @ file:///D:/bld/statsmodels_1612273795533/work
swifter==1.0.9
tblib==1.7.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.10.1
testpath==0.5.0
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1628668762525/work
toml==0.10.2
toolz==0.11.1
tornado @ file:///C:/ci/tornado_1606935947090/work
tqdm==4.62.1
traitlets==5.0.5
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1624965014186/work
ujson==4.1.0
UpSetPlot==0.4.4
urllib3 @ file:///tmp/build/80754af9/urllib3_1625084269274/work
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306165655/work
wincertstore==0.2
winkerberos==0.8.0
wordcloud==1.8.1
wrapt==1.12.1
xarray==0.19.0
xarray-spatial==0.2.7
xlrd==2.0.1
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1625570634446/work
